# Generated by Django 3.2.7 on 2021-12-02 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_h_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='h_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
