# Generated by Django 3.2.7 on 2021-12-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
