# Generated by Django 3.2.7 on 2021-12-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
