# Generated by Django 3.2.7 on 2021-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='h_bid',
            field=models.IntegerField(blank=True, default=models.IntegerField(), null=True),
        ),
    ]
