# Generated by Django 3.2.7 on 2021-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_h_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='h_bid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
